In [1]:
# RNNcell的使用
import torch

batch_size = 1
seq_len = 3
input_size = 4
hidden_size = 2

cell = torch.nn.RNNCell(input_size=input_size, hidden_size=hidden_size)

# (seq, batch, features)
dataset = torch.randn(seq_len, batch_size, input_size)
hidden = torch.zeros(batch_size, hidden_size)

for idx, input in enumerate(dataset):
    print('=' * 20, idx, '=' * 20)
    print('Input size: ', input.shape)
    hidden = cell(input, hidden)
    print('outputs size: ', hidden.shape)
    print(hidden)


==================== 0 ====================
Input size:  torch.Size([1, 4])
outputs size:  torch.Size([1, 2])
tensor([[-0.4079,  0.3582]], grad_fn=<TanhBackward0>)
==================== 1 ====================
Input size:  torch.Size([1, 4])
outputs size:  torch.Size([1, 2])
tensor([[-0.1538,  0.8657]], grad_fn=<TanhBackward0>)
==================== 2 ====================
Input size:  torch.Size([1, 4])
outputs size:  torch.Size([1, 2])
tensor([[-0.7359, -0.0997]], grad_fn=<TanhBackward0>)


In [2]:
# RNN的使用
import torch
batch_size = 1
seq_len = 3
input_size = 4
hidden_size = 2
num_layers = 1
cell = torch.nn.RNN(input_size=input_size, hidden_size=hidden_size,
num_layers=num_layers)
# (seqLen, batchSize, inputSize)
inputs = torch.randn(seq_len, batch_size, input_size)
hidden = torch.zeros(num_layers, batch_size, hidden_size)
out, hidden = cell(inputs, hidden)
print('Output size:', out.shape)
print('Output:', out)
print('Hidden size: ', hidden.shape)
print('Hidden: ', hidden)

Output size: torch.Size([3, 1, 2])
Output: tensor([[[-0.6788, -0.2607]],

        [[ 0.5818,  0.4645]],

        [[ 0.8616, -0.3624]]], grad_fn=<StackBackward0>)
Hidden size:  torch.Size([1, 1, 2])
Hidden:  tensor([[[ 0.8616, -0.3624]]], grad_fn=<StackBackward0>)


In [3]:
import torch
input_size = 4
hidden_size = 4
batch_size = 1

idx2char = ['e', 'h', 'l', 'o']
x_data = [1, 0, 2, 2, 3]
y_data = [3, 1, 2, 3, 2]
one_hot_lookup = [[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0],
[0, 0, 0, 1]]
x_one_hot = [one_hot_lookup[x] for x in x_data]
inputs = torch.Tensor(x_one_hot).view(-1, batch_size, input_size)
labels = torch.LongTensor(y_data).view(-1, 1)


In [ ]:
class Model(torch.nn.Module):
    def __init__(self, input_size, hidden_size, batch_size):
        super(Model, self).__init__()
        self.batch_size = batch_size
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.rnncell = torch.nn.RNNCell(input_size=self.input_size,
        hidden_size=self.hidden_size)
    def forward(self, input, hidden):
        hidden = self.rnncell(input, hidden)
        return hidden
    def init_hidden(self):
        return torch.zeros(self.batch_size, self.hidden_size)

net = Model(input_size, hidden_size, batch_size)


In [6]:
criterion = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(net.parameters(), lr=0.1)

In [ ]:
for epoch in range(15):
    loss = 0
    optimizer.zero_grad()
    hidden = net.init_hidden()
    print('Predicted string: ', end='')
    for input, label in zip(inputs, labels):
        hidden = net(input, hidden)
        loss += criterion(hidden, label)
        _, idx = hidden.max(dim=1)
        print(idx2char[idx.item()], end='')
    loss.backward()
    optimizer.step()
    print(', Epoch [%d/15] loss=%.4f' % (epoch+1, loss.item()))

# 用RNN模式也可以试试 

Predicted string: eeeee, Epoch [1/15] loss=9.1616
Predicted string: eelle, Epoch [2/15] loss=7.7158
Predicted string: helle, Epoch [3/15] loss=6.6707
Predicted string: hhlle, Epoch [4/15] loss=5.9201
Predicted string: hhloo, Epoch [5/15] loss=5.3216
Predicted string: hhlol, Epoch [6/15] loss=4.8252
Predicted string: ohlol, Epoch [7/15] loss=4.4533
Predicted string: ohlol, Epoch [8/15] loss=4.1644
Predicted string: ohool, Epoch [9/15] loss=3.9034
Predicted string: ohool, Epoch [10/15] loss=3.6751
Predicted string: ohool, Epoch [11/15] loss=3.4912
Predicted string: ohool, Epoch [12/15] loss=3.3286
Predicted string: ohool, Epoch [13/15] loss=3.1704
Predicted string: ohool, Epoch [14/15] loss=3.0235
Predicted string: ohool, Epoch [15/15] loss=2.8979
